# Generated by Django 4.1.4 on 2022-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
