# Generated by Django 4.1.4 on 2022-12-20 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty_fee_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('paymentdate', models.DateField(auto_now_add=True)),
                ('expirationdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Servicio')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
            ],
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.AddField(
            model_name='payment_user',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.services', verbose_name='Servicio del usuario'),
        ),
        migrations.AddField(
            model_name='payment_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='expired_payments',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.payment_user', verbose_name='Fecha de expiración de pago'),
        ),
    ]
