# Generated by Django 4.1.4 on 2022-12-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_payment_user_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_payments',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.payment_user'),
        ),
        migrations.AlterField(
            model_name='expired_payments',
            name='penalty_fee_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Importe de la multa'),
        ),
    ]
