# Generated by Django 4.1.4 on 2022-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_expired_payments_payment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_payments',
            name='penalty_fee_amount',
            field=models.FloatField(default=0.0, verbose_name='Importe de la multa'),
        ),
    ]
