# Generated by Django 4.1.4 on 2022-12-20 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_expired_payments_payment_user_services_delete_pagos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_user',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Monto a pagar'),
        ),
        migrations.AlterField(
            model_name='payment_user',
            name='expirationdate',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='payment_user',
            name='paymentdate',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='payment_user',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.services', verbose_name='ID del servicio'),
        ),
    ]
