# Generated by Django 4.1.4 on 2022-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_expired_payments_penalty_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_user',
            name='amount',
            field=models.FloatField(verbose_name='Monto a pagar'),
        ),
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos/', verbose_name='Logo'),
        ),
    ]
