# Generated by Django 4.1.4 on 2022-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_payment_user_amount_alter_services_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='prefix',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Prefijo'),
        ),
    ]
