# Generated by Django 4.1.4 on 2022-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_alter_services_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos/', verbose_name='Logo'),
        ),
    ]
