# Generated by Django 4.1.4 on 2022-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_alter_services_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='services',
            name='prefix',
            field=models.CharField(max_length=3, unique=True, verbose_name='Prefijo'),
        ),
    ]
